version: "3.3"

services: 
  a-informacion:
    restart: always 
    build: .
    labels: 
      - "traefik.http.routers.a-informacion.rule=Host(`a-informacion.restoner-api.fun`)"
    networks:
      - backend
    links:
      - mongo
  mongo:
    image: mongo
    restart: always
    networks:
      - backend
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbbusiness_user
      MONGO_INITDB_ROOT_PASSWORD: mongodb1151
  mongo-express:
    image: "mongo-express:1.0.0-alpha.4"
    restart: always
    ports:
      - "90:8081"
    networks:
      - backend
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongobusiness_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: adgadsfg234GWe5Ggwf34G435g3
      ME_CONFIG_BASICAUTH_USERNAME: mongobasicauthfw2345f
      ME_CONFIG_BASICAUTH_PASSWORD: dasd23GGFa435fuj6c
      ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"
      ME_CONFIG_MONGODB_URL: mongodb://mongodbbusiness_user:mongodb1151@mongo:27017/
  traefik: # apache.app.test - nginx.app.test
    image: traefik:v2.3.6
    networks:
      - backend
    ports: 
      - 80:80
      - 443:443
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/traefik.yml
      - ./acme.json:/acme.json
      
networks:
  backend:
    driver: bridge
    ipam: 
      driver: default 








